---
# https://github.com/DavidAnson/markdownlint/blob/main/schema/.markdownlint.yaml
# MD013/line-length - Line length
MD013: false

# MD024/no-duplicate-heading/no-duplicate-header - Multiple headings with the same content
MD024:
  # Only check sibling headings
  siblings_only: true

# MD033/no-inline-html - Inline HTML
MD033: false

# MD036/emphasis-used-as-heading
MD036: false

# MD060/table-column-style
MD060: false
