#!/usr/bin/env bash
#
# worktree-setup.sh - Prepare a git worktree for development
#
# This script sets up the development environment for a new worktree by:
# 1. Installing dependencies via `just install`
# 2. Creating .env files with randomized ports to avoid conflicts with other worktrees
#
# Usage:
#   ./scripts/worktree-setup.sh
#
# The script generates random ports in these ranges:
#   - API server: 8000-8999
#   - Web server: 5173-6172
#   - Docker stack: 8080-8179
#

set -euo pipefail

# Change to repository root (script may be called from anywhere)
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(dirname "$SCRIPT_DIR")"
cd "$REPO_ROOT"

echo "=== VintageStory Server Worktree Setup ==="
echo "Repository root: $REPO_ROOT"
echo ""

# Generate random ports
# API: 8000-8999 range
API_PORT=$((8000 + RANDOM % 1000))
# Web: 5173-6172 range
WEB_PORT=$((5173 + RANDOM % 1000))
# Docker: 8080-8179 range (for containerized stack)
DOCKER_PORT=$((8080 + RANDOM % 100))

echo "Generated ports:"
echo "  API server:   $API_PORT"
echo "  Web server:   $WEB_PORT"
echo "  Docker stack: $DOCKER_PORT"
echo ""

# Generate a random API key for development
DEV_API_KEY="dev-$(openssl rand -hex 16)"

# Create root .env file
echo "Creating .env file..."
cat > .env << EOF
# Auto-generated by worktree-setup.sh
# Ports randomized to avoid conflicts with other worktrees

# API Authentication
VS_API_KEY_ADMIN=$DEV_API_KEY
VS_API_KEY_MONITOR=monitor-$(openssl rand -hex 16)
VS_API_KEY=$DEV_API_KEY

# CORS - allow both API and web dev server origins
VS_CORS_ORIGINS="http://localhost:$WEB_PORT,http://localhost:$API_PORT"

# Development settings
VS_GAME_VERSION=stable
VS_DEBUG=true

# UV link mode
UV_LINK_MODE=copy

# Vite settings (for web frontend)
VITE_API_KEY=$DEV_API_KEY
VITE_API_BASE_URL="http://localhost:$API_PORT"

# Port configuration (used by dev servers and Docker)
API_PORT=$API_PORT
WEB_PORT=$WEB_PORT
DOCKER_PORT=$DOCKER_PORT
EOF

# Create web/.env file
echo "Creating web/.env file..."
cat > web/.env << EOF
# Auto-generated by worktree-setup.sh
# Must match settings in root .env

# API Key for authentication
VITE_API_KEY=$DEV_API_KEY

# API Base URL - points to local dev API server
VITE_API_BASE_URL=http://localhost:$API_PORT
EOF

echo ""
echo "Installing dependencies..."
just install

echo ""
echo "=== Setup Complete ==="
echo ""
echo "To start development servers:"
echo "  API:  just dev-api"
echo "  Web:  just dev-web"
echo ""
echo "Ports are configured in .env and used automatically by just recipes."
