"""Machine-readable error codes for API responses."""


class ErrorCode:
    """Centralized error codes used across the API.

    These codes are returned in error responses for machine parsing.
    Human-readable messages accompany them for debugging.
    """

    # Authentication
    UNAUTHORIZED = "UNAUTHORIZED"
    FORBIDDEN = "FORBIDDEN"

    # Server lifecycle
    SERVER_NOT_RUNNING = "SERVER_NOT_RUNNING"
    SERVER_NOT_INSTALLED = "SERVER_NOT_INSTALLED"
    SERVER_ALREADY_RUNNING = "SERVER_ALREADY_RUNNING"
    SERVER_START_FAILED = "SERVER_START_FAILED"
    SERVER_STOP_FAILED = "SERVER_STOP_FAILED"
    SERVER_ALREADY_STOPPED = "SERVER_ALREADY_STOPPED"

    # Mods
    MOD_NOT_FOUND = "MOD_NOT_FOUND"
    MOD_NOT_INSTALLED = "MOD_NOT_INSTALLED"
    MOD_INCOMPATIBLE = "MOD_INCOMPATIBLE"
    MOD_ALREADY_INSTALLED = "MOD_ALREADY_INSTALLED"
    MOD_STATE_CORRUPT = "MOD_STATE_CORRUPT"
    MOD_FILE_CORRUPT = "MOD_FILE_CORRUPT"
    INVALID_SLUG = "INVALID_SLUG"

    # Config
    INVALID_CONFIG = "INVALID_CONFIG"
    CONFIG_NOT_FOUND = "CONFIG_NOT_FOUND"

    # External APIs
    EXTERNAL_API_ERROR = "EXTERNAL_API_ERROR"
    EXTERNAL_API_TIMEOUT = "EXTERNAL_API_TIMEOUT"
    DOWNLOAD_FAILED = "DOWNLOAD_FAILED"

    # Mod Installation
    MOD_VERSION_NOT_FOUND = "MOD_VERSION_NOT_FOUND"

    # Server installation
    INVALID_VERSION = "INVALID_VERSION"
    VERSION_NOT_FOUND = "VERSION_NOT_FOUND"
    SERVER_ALREADY_INSTALLED = "SERVER_ALREADY_INSTALLED"
    INSTALLATION_FAILED = "INSTALLATION_FAILED"
    INSTALLATION_IN_PROGRESS = "INSTALLATION_IN_PROGRESS"
    CHECKSUM_MISMATCH = "CHECKSUM_MISMATCH"

    # General
    VALIDATION_ERROR = "VALIDATION_ERROR"
    INTERNAL_ERROR = "INTERNAL_ERROR"
